[package]
name = "riir"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.4"
base58 = "0.2.0"
crunchy = "0.2.2"
itertools = "0.12.1"
num-bigint = "0.4.4"
num-traits = "0.2.18"
sha2 = { version = "0.10.8", features = ["asm"] }
